# Generated by Django 5.2.1 on 2025-06-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
